/*
Enter your query here.
*/
(SELECT CITY, LENGTH(CITY) AS name_length
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1)

UNION ALL

(SELECT CITY, LENGTH(CITY) AS name_length
FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION)
ORDER BY CITY
LIMIT 1)